name: chem1147
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=2.137
  - blas-devel=3.9.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - expat=2.7.1
  - joblib=1.5.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=20.1.8
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.30
  - libxgboost=3.0.5
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - ncurses=6.5
  - openblas=0.3.30
  - openssl=3.5.4
  - pip=25.2
  - py-xgboost=3.0.5
  - python=3.10.18
  - readline=8.3
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - wheel=0.45.1
  - xgboost=3.0.5
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - alembic==1.17.0
      - biopython==1.86
      - brendapyrser==0.0.2
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - colorlog==6.10.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.60.1
      - idna==3.11
      - kiwisolver==1.4.9
      - lightgbm==4.6.0
      - llvmlite==0.45.1
      - mako==1.3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - numba==0.62.1
      - numpy==2.2.6
      - optuna==4.5.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - pubchempy==1.0.5
      - pyarrow==22.0.0
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - rdkit-pypi==2022.9.5
      - requests==2.32.5
      - seaborn==0.13.2
      - six==1.17.0
      - sqlalchemy==2.0.44
      - tomli==2.3.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
prefix: /Users/yang/ENTER/envs/chem1147
